---
title: "visualizations"
author: "Lavonne Hoang"
date: "4/20/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(GGally)
library(scales)
library(dplyr)
library(magrittr)
library(tidyverse)
```

```{r}
coronavirus <- readRDS("data/coronavirus.Rds")
coronavirus <- coronavirus[,colSums(is.na(coronavirus))<nrow(coronavirus)]
coronavirus <- na.omit(coronavirus)
coronavirus$Position <- as.factor(coronavirus$Position)
```

```{r}
# scaled<-data.frame(coronavirus=scale(coronavirus[,c("danceability","energy","key","loudness","mode","speechiness",
#                                                     "acousticness","instrumentalness","liveness",
#                                                     "valence","tempo","cases","deaths")]))
# fit <- polr(Position~danceability+energy+key+loudness+mode+speechiness+acousticness+instrumentalness+liveness+valence+tempo+cases+deaths, data=coronavirus,Hess = TRUE)

```



```{r}
averaged <- coronavirus %>%
  group_by(date) %>%
  summarise(danceability = mean(danceability), energy = mean(energy), key = mean(key), loudness = mean(loudness), mode = mean(mode), speechiness = mean(speechiness), acousticness = mean(acousticness), instrumentalness = mean(instrumentalness), liveness = mean(instrumentalness), valence = mean(valence), tempo = mean(tempo), cases = mean(cases), deaths = mean(deaths))
```

```{r}
ggcorr(averaged)
```

```{r}
averaged %>%
  dplyr::select(date, danceability, energy, key, speechiness, instrumentalness, liveness, valence, tempo, cases) %>%
  gather(key = "var", value = "value", -date, -cases) %>%
  ggplot(aes(x = value, y = cases)) +
    geom_point() +
    facet_wrap(~ var, scales = "free") +
    theme_minimal() + 
  labs(title = "Number of Average Cases Across Different Values of Audio Features",
       x = "Values",
       y = "Average Cases Per Day")

```

```{r}
averaged$log_cases <- log(averaged$cases)
fit<- lm(log_cases~danceability+energy+instrumentalness+key+liveness+speechiness+tempo+valence, data=averaged)
step <- stepAIC(fit, direction="both")
step$anova # display results
summary(step)
```

```{r}
library(ggeffects)
ggPredict(step,colorAsFactor = TRUE,interactive=TRUE)
```
